import React, { useState, useMemo } from 'react';
import { useOutletContext } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useQuery } from '@tanstack/react-query';
import PageHeader from '@/components/layout/PageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { formatRankName } from '@/lib/constants';
import { ClipboardList, Check, AlertTriangle, Copy } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

export default function ParadeState() {
  const { user } = useOutletContext();
  const [outOfCamp, setOutOfCamp] = useState('');
  const [previewing, setPreviewing] = useState(false);

  const { data: allUsers = [] } = useQuery({
    queryKey: ['all-users', user?.unit],
    queryFn: () => base44.entities.User.filter({ unit: user?.unit }),
    enabled: !!user?.unit,
  });

  const { data: activeStatuses = [] } = useQuery({
    queryKey: ['active-statuses', user?.unit],
    queryFn: () => base44.entities.StatusReport.filter({ unit: user?.unit, status: 'active' }),
    enabled: !!user?.unit,
  });

  const { data: approvedStatuses = [] } = useQuery({
    queryKey: ['approved-statuses', user?.unit],
    queryFn: () => base44.entities.StatusReport.filter({ unit: user?.unit, status: 'approved' }),
    enabled: !!user?.unit,
  });

  const totalStrength = allUsers.length;
  const outOfCampNum = parseInt(outOfCamp) || 0;

  const rsoCount = [...activeStatuses, ...approvedStatuses].filter(s => s.type === 'RSO').length;
  const maCount = [...activeStatuses, ...approvedStatuses].filter(s => s.type === 'MA').length;
  const rsiCount = [...activeStatuses, ...approvedStatuses].filter(s => s.type === 'RSI').length;

  const validOutOfCamp = outOfCampNum >= 0 && outOfCampNum <= totalStrength;
  const inCamp = totalStrength - outOfCampNum - rsoCount;

  const generateReport = () => {
    const date = format(new Date(), 'dd MMM yyyy').toUpperCase();
    const time = format(new Date(), 'HHmm');
    return `📊 PARADE STATE
${user?.unit || 'UNIT'}
Date: ${date}
Time: ${time}h
────────────────
Total Strength: ${totalStrength}
In Camp: ${Math.max(inCamp, 0)}
Out of Camp: ${outOfCampNum}
────────────────
RSO: ${rsoCount}
MA: ${maCount}
RSI: ${rsiCount}
────────────────
${[...activeStatuses, ...approvedStatuses].map(s => 
  `${s.type}: ${formatRankName(s.personnel_rank, s.personnel_name)}${s.diagnosis ? ' (' + s.diagnosis + ')' : ''}`
).join('\n')}
────────────────
Generated by: ${formatRankName(user?.rank, user?.full_name)}`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateReport());
    toast.success('Copied to clipboard');
  };

  const handleSend = async () => {
    await base44.entities.AuditLog.create({
      action: 'parade_state_generated',
      category: 'parade',
      details: generateReport(),
      performed_by: user?.email,
      unit: user?.unit,
    });

    await base44.entities.Notification.create({
      title: 'Parade State Generated',
      message: `Parade state for ${format(new Date(), 'dd MMM')} generated by ${user?.full_name}`,
      type: 'info',
      category: 'admin',
      recipient_unit: user?.unit,
    });

    toast.success('Parade state sent');
  };

  return (
    <div>
      <PageHeader title="Parade State" backTo="/admin" subtitle="Generate parade state report" />
      <div className="px-4 py-4 space-y-5">
        <div className="space-y-2">
          <Label className="text-sm font-medium">Out of Camp Count</Label>
          <Input
            type="number"
            min="0"
            placeholder="Enter count"
            value={outOfCamp}
            onChange={(e) => setOutOfCamp(e.target.value)}
            className="text-center text-lg font-mono"
          />
          {!validOutOfCamp && outOfCamp !== '' && (
            <Alert variant="destructive" className="py-2">
              <AlertTriangle className="h-4 w-4" />
              <AlertDescription className="text-xs">
                Count cannot be negative or exceed total strength ({totalStrength}).
              </AlertDescription>
            </Alert>
          )}
        </div>

        <div className="grid grid-cols-3 gap-2">
          <Card><CardContent className="p-3 text-center">
            <p className="text-xs text-muted-foreground">RSO</p>
            <p className="text-lg font-bold">{rsoCount}</p>
          </CardContent></Card>
          <Card><CardContent className="p-3 text-center">
            <p className="text-xs text-muted-foreground">MA</p>
            <p className="text-lg font-bold">{maCount}</p>
          </CardContent></Card>
          <Card><CardContent className="p-3 text-center">
            <p className="text-xs text-muted-foreground">RSI</p>
            <p className="text-lg font-bold">{rsiCount}</p>
          </CardContent></Card>
        </div>

        <Button className="w-full" onClick={() => setPreviewing(true)} disabled={!validOutOfCamp || outOfCamp === ''}>
          <ClipboardList className="h-4 w-4 mr-1" />Preview Parade State
        </Button>

        {previewing && (
          <div className="space-y-3">
            <Card className="bg-muted/30">
              <CardContent className="p-4">
                <pre className="text-xs whitespace-pre-wrap font-mono leading-relaxed">{generateReport()}</pre>
              </CardContent>
            </Card>
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1" onClick={handleCopy}>
                <Copy className="h-4 w-4 mr-1" />Copy
              </Button>
              <Button className="flex-1" onClick={handleSend}>
                <Check className="h-4 w-4 mr-1" />Send
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}